version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5086:5086"               # host 5086  →  container 5086
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ./backend/expenses.db:/app/expenses.db  

  frontend:
    build:
      context: .                  
      dockerfile: ./Dockerfile   
    ports:
      - "3000:80"
    depends_on:
      - backend
