version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production    
    volumes:
      - ./backend/expenses.db:/app/expenses.db  

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
